### PR TITLE
Use the right element to get LitElement from

### PR DESCRIPTION
**Pull request by bramkragten**
The `home-assistant` element is not a normal `LitElement`, but has a bunch of mixins giving unwanted side effects.

Besides that, `hui-view` is no longer a `LitElement` but a `UpdatingElement`, so should not be used as a fallback.

### CODE REVIEW

**Comment by kalkih** [comment]
Great, thanks!

**Comment by hmmbob** [comment]
@kalkih could you possibly tag a new release with this fix? Without it, the card is making my theme revert to dark mode everytime the card is displayed 😉 

I only have it on 2021.5.0 beta release so far, which makes me believe more users will be affected as soon as 2021.5 ships (coming Wednesday).

Thanks for creating great stuff!

**Comment by kalkih** [comment]
Hey @hmmbob , thanks for letting me know, will create a release later today 👍

**Comment by hmmbob** [comment]
Much appreciated, thanks!

**Comment by Mariusthvdb** [comment]
> @kalkih could you possibly tag a new release with this fix? Without it, the card is making my theme revert to dark mode everytime the card is displayed 😉
> 
> I only have seen the issue on 2021.5.0 beta release so far, which makes me believe more users will be affected as soon as 2021.5 ships (coming Wednesday).
> 
> Thanks for creating great stuff!

yes! thats exactly what I saw yesterday, couldn't find the logic to it though...more-over it doesnt do that right now, so some mystery still going on...

**Comment by bramkragten** [comment]
> @bramkragten please allow me to ask if that is something that needs to be changed [here](https://github.com/Mariusthvdb/custom-ui/blob/31c53ddd737ef5f7c0307c26d6a4fe9665691301/custom-ui.js#L231) and [here](https://github.com/Mariusthvdb/custom-ui/blob/31c53ddd737ef5f7c0307c26d6a4fe9665691301/custom-ui.js#L368) in custom-ui too?

No.

**Pull request merged**
